import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { pool } from './db/pool.js';
import OpenAI from 'openai';
import { buildFallbackModule, buildPrompt, extractSources, recommendLearningModel } from './services/moduleGenerator.js';
import { buildFallbackCurriculum, buildCurriculumPrompt, extractCurriculumSources } from './services/curriculumGenerator.js';
dotenv.config();
const app=express();
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));
app.use(express.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname,'../frontend')));
const q=(text,params=[])=>pool.query(text,params);
const token=u=>jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'});
app.get('/api/classes',async(req,res)=>{try{const {education_level,grade,academic_year,semester}=req.query;const r=await q(`SELECT * FROM classes WHERE ($1::text IS NULL OR education_level=$1) AND ($2::text IS NULL OR grade=$2) AND ($3::text IS NULL OR academic_year=$3) AND ($4::text IS NULL OR semester=$4) ORDER BY education_level,grade,section,name`,[education_level||null,grade||null,academic_year||null,semester||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/classes',async(req,res)=>{try{const {school_id,name,education_level,grade,section,major,academic_year,semester}=req.body;if(!name||!education_level||!grade)return res.status(400).json({error:'Nama kelas, jenjang, dan tingkat wajib'});const r=await q(`INSERT INTO classes(school_id,name,education_level,grade,section,major,academic_year,semester) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[school_id||null,name,education_level,grade,section||'A',major||null,academic_year||null,semester||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/subjects',async(req,res)=>{try{const {school_id}=req.query;const r=await q('SELECT * FROM subjects WHERE ($1::uuid IS NULL OR school_id=$1::uuid) ORDER BY name',[school_id||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/health',async(_req,res)=>{try{await q('SELECT 1');res.json({ok:true,database:true});}catch(e){res.status(503).json({ok:false,database:false,error:e.message});}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Nama, email, password wajib'});const hash=await bcrypt.hash(password,12);const r=await q('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[name,email.toLowerCase(),hash,'teacher']);res.status(201).json({user:r.rows[0],token:token(r.rows[0])});}catch(e){res.status(400).json({error:e.code==='23505'?'Email sudah terdaftar':e.message});}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const r=await q('SELECT * FROM users WHERE email=$1',[email?.toLowerCase()]);if(!r.rows[0]||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Email atau password salah'});const u=r.rows[0];res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role},token:token(u)});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/students',async(_req,res)=>{try{const r=await q('SELECT * FROM students ORDER BY name');res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/students',async(req,res)=>{try{const {class_id,nis,nisn,name,gender,birth_place,birth_date,address,parent_name,parent_phone,status}=req.body;const r=await q(`INSERT INTO students(class_id,nis,nisn,name,gender,birth_place,birth_date,address,parent_name,parent_phone,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[class_id||null,nis||null,nisn||null,name,gender||null,birth_place||null,birth_date||null,address||null,parent_name||null,parent_phone||null,status||'aktif']);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/students/:id',async(req,res)=>{try{const {name,nis,nisn,gender,address,parent_name,parent_phone,status,class_id}=req.body;const r=await q(`UPDATE students SET name=COALESCE($1,name),nis=$2,nisn=$3,gender=$4,address=$5,parent_name=$6,parent_phone=$7,status=$8,class_id=$9,updated_at=NOW() WHERE id=$10 RETURNING *`,[name,nis||null,nisn||null,gender||null,address||null,parent_name||null,parent_phone||null,status||'aktif',class_id||null,req.params.id]);if(!r.rows[0])return res.sendStatus(404);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.delete('/api/students/:id',async(req,res)=>{try{await q('DELETE FROM students WHERE id=$1',[req.params.id]);res.sendStatus(204);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/attendance',async(req,res)=>{try{const {date,class_id}=req.query;const r=await q(`SELECT a.*,s.name,s.nis FROM attendance a JOIN students s ON s.id=a.student_id WHERE ($1::date IS NULL OR a.date=$1::date) AND ($2::uuid IS NULL OR a.class_id=$2::uuid) ORDER BY s.name`,[date||null,class_id||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/attendance/bulk',async(req,res)=>{try{const {date,class_id,items=[]}=req.body;for(const x of items)await q(`INSERT INTO attendance(class_id,student_id,date,status,note) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id,date) DO UPDATE SET status=EXCLUDED.status,note=EXCLUDED.note,class_id=EXCLUDED.class_id,updated_at=NOW()`,[class_id,x.student_id,date,x.status,x.note||null]);res.json({saved:items.length});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/journals',async(_req,res)=>{try{res.json((await q('SELECT * FROM journals ORDER BY date DESC,created_at DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/journals',async(req,res)=>{try{const {teacher_id,class_id,subject_id,date,topic,activities,reflection,attendance_summary}=req.body;const r=await q(`INSERT INTO journals(teacher_id,class_id,subject_id,date,topic,activities,reflection,attendance_summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[teacher_id||null,class_id||null,subject_id||null,date,topic,activities,reflection||null,attendance_summary||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/documents',async(_req,res)=>{try{res.json((await q('SELECT * FROM documents ORDER BY updated_at DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/documents',async(req,res)=>{try{const {teacher_id,class_id,subject_id,type,title,content,status}=req.body;const r=await q(`INSERT INTO documents(teacher_id,class_id,subject_id,type,title,content,status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[teacher_id||null,class_id||null,subject_id||null,type||'modul_ajar',title,content||'',status||'draft']);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/documents/:id',async(req,res)=>{try{const {title,content,status}=req.body;const r=await q('UPDATE documents SET title=$1,content=$2,status=$3,updated_at=NOW() WHERE id=$4 RETURNING *',[title,content||'',status||'draft',req.params.id]);if(!r.rows[0])return res.sendStatus(404);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/assessments',async(_req,res)=>{try{res.json((await q('SELECT * FROM assessments ORDER BY date DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/assessments',async(req,res)=>{try{const {class_id,subject_id,teacher_id,type,title,date,description}=req.body;const r=await q(`INSERT INTO assessments(class_id,subject_id,teacher_id,type,title,date,description) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[class_id||null,subject_id||null,teacher_id||null,type,title,date,description||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/assessments/:id/scores',async(req,res)=>{try{res.json((await q('SELECT x.*,s.name,s.nis FROM assessment_scores x JOIN students s ON s.id=x.student_id WHERE assessment_id=$1 ORDER BY s.name',[req.params.id])).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/generate-curriculum',async(req,res)=>{try{const {docType='CP',level='SD',grade=5,section='A',subject='Matematika',semester='Ganjil',academicYear='2026/2027',chapter='',jpPerWeek=4,weeksGanjil=18,weeksGenap=18,jpPerMeeting=2,meetingMinutes=35}=req.body||{};const payload={docType,level,grade:Number(grade),section,subject,semester,academicYear,chapter,jpPerWeek:Number(jpPerWeek),weeksGanjil:Number(weeksGanjil),weeksGenap:Number(weeksGenap),jpPerMeeting:Number(jpPerMeeting),meetingMinutes:Number(meetingMinutes)};if(process.env.OPENAI_API_KEY){const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id','rumah.pendidikan.go.id']}}],input:buildCurriculumPrompt(payload)});return res.json({mode:'internet-ai',content:response.output_text||'',sources:extractCurriculumSources(response)});}return res.json({mode:'template',content:buildFallbackCurriculum(payload),sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur; dokumen dibuat dengan generator lokal. Tambahkan OPENAI_API_KEY untuk pencarian Internet + AI.'});}catch(e){console.error(e);res.status(500).json({error:'Gagal membuat dokumen kurikulum',detail:e.message});}});
function moduleSectionsFallback(payload){
  const {level='SD',grade=5,subject='Matematika',chapter='Materi Pembelajaran',semester='Ganjil',academicYear='2026/2027',allocationMinutes=70,model='AUTO'}=payload;
  const phase=level==='SD'?(grade<=2?'A':grade<=4?'B':'C'):level==='SMP'?'D':'E';
  const m=model==='AUTO'?'Discovery':model;
  return {
    identitas:`Jenjang: ${level}\nKelas: ${grade}\nRombel: ${payload.section||'A'}\nMata Pelajaran: ${subject}\nMateri/Bab: ${chapter}\nFase: ${phase}\nSemester: ${semester}\nTahun Ajaran: ${academicYear}\nAlokasi Waktu: ${allocationMinutes} menit`,
    cp:`Peserta didik mencapai kompetensi pada Fase ${phase} sesuai Capaian Pembelajaran resmi ${subject}. Sesuaikan rumusan ini dengan dokumen CP resmi dan konteks satuan pendidikan.`,
    tp:`1. Peserta didik menjelaskan konsep utama ${chapter} dengan istilah yang tepat.\n2. Peserta didik menerapkan konsep ${chapter} pada situasi kontekstual.\n3. Peserta didik mengomunikasikan hasil kerja dengan alasan/bukti yang relevan.`,
    atp:`1. Aktivasi pengetahuan awal tentang ${chapter}.\n2. Eksplorasi konsep dan contoh.\n3. Latihan terbimbing dan kolaboratif.\n4. Penerapan pada masalah kontekstual.\n5. Presentasi, refleksi, dan tindak lanjut.`,
    profil:`Bernalar kritis; mandiri; gotong royong; kreatif.\nPenguatan dilakukan melalui diskusi, pemecahan masalah, refleksi, dan presentasi.`,
    sarpras:`Buku teks/sumber resmi; papan tulis/proyektor; LKPD; alat tulis; perangkat digital bila tersedia; lingkungan belajar yang aman dan inklusif.`,
    model:`${m}\nAlasan: model dipilih agar peserta didik aktif mengeksplorasi konsep, menerapkan pengetahuan, dan mengomunikasikan hasil.`,
    langkah:`Pendahuluan (10 menit): salam, apersepsi, asesmen awal, penyampaian tujuan.\n\nInti: orientasi masalah/konsep, eksplorasi, diskusi/latihan, penerapan, presentasi dan umpan balik.\n\nPenutup (10 menit): rangkuman, refleksi, tindak lanjut, dan informasi pembelajaran berikutnya.`,
    asesmen:`Diagnostik: pertanyaan pemantik/cek pengetahuan awal.\nFormatif: observasi, diskusi, LKPD, kuis, dan umpan balik.\nSumatif: tes/produk/performa sesuai tujuan pembelajaran.\nRubrik: ketepatan konsep, proses, komunikasi, dan kemandirian.`,
    lampiran:`LKPD: identitas, petunjuk, stimulus, langkah kerja, tabel hasil, refleksi.\nBahan ajar: ringkasan konsep, contoh, latihan, glosarium.\nLampiran asesmen: instrumen, kunci/rubrik, dan daftar pustaka.`
  };
}

function buildModuleSectionsPrompt(payload){
  return `Anda adalah perancang perangkat ajar Indonesia. Buat 10 bagian Modul Ajar untuk ${payload.level} kelas ${payload.grade}, ${payload.subject}, materi ${payload.chapter}, semester ${payload.semester}, tahun ${payload.academicYear}. Gunakan sumber resmi pendidikan yang ditemukan lewat web search, prioritaskan kurikulum.kemdikbud.go.id, kemendikdasmen.go.id, kemdikbud.go.id, dan Rumah Pendidikan. Jangan menyalin panjang; sintesis dan adaptasikan. Kembalikan HANYA JSON valid dengan objek keys: identitas, cp, tp, atp, profil, sarpras, model, langkah, asesmen, lampiran, sources. Setiap value bagian adalah string siap diedit guru. sources adalah array URL sumber. Pastikan CP/ketentuan kurikulum diberi catatan bahwa guru perlu memverifikasi kesesuaian dengan dokumen resmi terbaru. Hubungkan TP dengan CP, ATP dengan TP, langkah dengan model, dan asesmen dengan TP. Sertakan pembelajaran mendalam/diferensiasi bila relevan, tetapi jangan mengada-ada regulasi. Data: ${JSON.stringify(payload)}`;
}

app.post('/api/generate-module-sections',async(req,res)=>{
  try{
    const payload={level:'SD',grade:5,section:'A',subject:'Matematika',chapter:'Materi Pembelajaran',semester:'Ganjil',academicYear:'2026/2027',allocationMinutes:70,model:'AUTO',...(req.body||{})};
    const fallback=moduleSectionsFallback(payload);
    if(process.env.OPENAI_API_KEY){
      const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
      const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id','rumah.pendidikan.go.id']}}],input:buildModuleSectionsPrompt(payload)});
      let raw=(response.output_text||'').trim().replace(/^```json\s*/,'').replace(/```$/,'').trim();
      const parsed=JSON.parse(raw);
      const sections={...fallback,...parsed};
      return res.json({mode:'internet-ai',sections,sources:Array.isArray(parsed.sources)?parsed.sources:[],notice:'10 bagian dibuat AI berdasarkan sumber Internet pendidikan yang ditelusuri. Periksa dan sesuaikan sebelum digunakan.'});
    }
    return res.json({mode:'template',sections:fallback,sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur. Sistem menggunakan generator lokal. Atur OPENAI_API_KEY agar 10 bagian dibuat dengan Internet + AI.'});
  }catch(e){console.error(e);res.status(500).json({error:'Gagal generate 10 bagian modul ajar',detail:e.message});}
});
app.post('/api/generate-module',async(req,res)=>{try{const {level='SD',grade=5,section='A',subject='Matematika',chapter='Materi Pembelajaran',model='AUTO',semester='Ganjil',academicYear='2026/2027',allocationMinutes,linkedCP='',linkedTP='',linkedATP='',linkedProsem='',linkedProta=''}=req.body||{};if(!chapter||!subject)return res.status(400).json({error:'Mata pelajaran dan materi wajib diisi'});const recommendation=recommendLearningModel({subject,chapter,linkedTP,linkedATP}); const selectedModel=model==='AUTO'?recommendation.model:model; const payload={level,grade:Number(grade),section,subject,chapter,model:selectedModel,semester,academicYear,allocationMinutes:Number(allocationMinutes)||undefined,linkedCP,linkedTP,linkedATP,linkedProsem,linkedProta};if(process.env.OPENAI_API_KEY){const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id']}}],input:buildPrompt(payload)});const content=response.output_text||'';const sources=extractSources(response);return res.json({mode:'internet-ai',content,sources,model:selectedModel,modelRationale:recommendation.rationale,integrated:true,includes:['LKPD','Bahan Ajar','Asesmen']});}const content=buildFallbackModule(payload);return res.json({mode:'template',content,model:selectedModel,modelRationale:recommendation.rationale,sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur; modul dibuat dengan generator lokal. Tambahkan OPENAI_API_KEY untuk pencarian Internet + AI.'});}catch(e){console.error(e);res.status(500).json({error:'Gagal membuat modul ajar',detail:e.message});}});
app.post('/api/assessments/:id/scores',async(req,res)=>{try{const items=req.body.items||[];for(const x of items)await q(`INSERT INTO assessment_scores(assessment_id,student_id,score,note) VALUES($1,$2,$3,$4) ON CONFLICT(assessment_id,student_id) DO UPDATE SET score=EXCLUDED.score,note=EXCLUDED.note,updated_at=NOW()`,[req.params.id,x.student_id,x.score,x.note||null]);res.json({saved:items.length});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api',(_req,res)=>res.json({name:'Pusat Administrasi Guru API',version:'3.0',status:'running'}));
app.get('/{*splat}',(_req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));
app.use((err,_req,res,_next)=>res.status(500).json({error:err.message}));
const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`Pusat Administrasi Guru running on port ${port}`));
