import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { pool } from './db/pool.js';
import OpenAI from 'openai';
import { buildFallbackModule, buildPrompt, extractSources, recommendLearningModel } from './services/moduleGenerator.js';
import { buildFallbackCurriculum, buildCurriculumPrompt, extractCurriculumSources } from './services/curriculumGenerator.js';
dotenv.config();
const app=express();
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));
app.use(express.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname,'../frontend')));
const q=(text,params=[])=>pool.query(text,params);
const token=u=>jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'});
app.get('/api/classes',async(req,res)=>{try{const {education_level,grade,academic_year,semester}=req.query;const r=await q(`SELECT * FROM classes WHERE ($1::text IS NULL OR education_level=$1) AND ($2::text IS NULL OR grade=$2) AND ($3::text IS NULL OR academic_year=$3) AND ($4::text IS NULL OR semester=$4) ORDER BY education_level,grade,section,name`,[education_level||null,grade||null,academic_year||null,semester||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/classes',async(req,res)=>{try{const {school_id,name,education_level,grade,section,major,academic_year,semester}=req.body;if(!name||!education_level||!grade)return res.status(400).json({error:'Nama kelas, jenjang, dan tingkat wajib'});const r=await q(`INSERT INTO classes(school_id,name,education_level,grade,section,major,academic_year,semester) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[school_id||null,name,education_level,grade,section||'A',major||null,academic_year||null,semester||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/subjects',async(req,res)=>{try{const {school_id}=req.query;const r=await q('SELECT * FROM subjects WHERE ($1::uuid IS NULL OR school_id=$1::uuid) ORDER BY name',[school_id||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/health',async(_req,res)=>{try{await q('SELECT 1');res.json({ok:true,database:true});}catch(e){res.status(503).json({ok:false,database:false,error:e.message});}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Nama, email, password wajib'});const hash=await bcrypt.hash(password,12);const r=await q('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[name,email.toLowerCase(),hash,'teacher']);res.status(201).json({user:r.rows[0],token:token(r.rows[0])});}catch(e){res.status(400).json({error:e.code==='23505'?'Email sudah terdaftar':e.message});}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const r=await q('SELECT * FROM users WHERE email=$1',[email?.toLowerCase()]);if(!r.rows[0]||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Email atau password salah'});const u=r.rows[0];res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role},token:token(u)});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/students',async(_req,res)=>{try{const r=await q('SELECT * FROM students ORDER BY name');res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/students',async(req,res)=>{try{const {class_id,nis,nisn,name,gender,birth_place,birth_date,address,parent_name,parent_phone,status}=req.body;const r=await q(`INSERT INTO students(class_id,nis,nisn,name,gender,birth_place,birth_date,address,parent_name,parent_phone,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[class_id||null,nis||null,nisn||null,name,gender||null,birth_place||null,birth_date||null,address||null,parent_name||null,parent_phone||null,status||'aktif']);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/students/:id',async(req,res)=>{try{const {name,nis,nisn,gender,address,parent_name,parent_phone,status,class_id}=req.body;const r=await q(`UPDATE students SET name=COALESCE($1,name),nis=$2,nisn=$3,gender=$4,address=$5,parent_name=$6,parent_phone=$7,status=$8,class_id=$9,updated_at=NOW() WHERE id=$10 RETURNING *`,[name,nis||null,nisn||null,gender||null,address||null,parent_name||null,parent_phone||null,status||'aktif',class_id||null,req.params.id]);if(!r.rows[0])return res.sendStatus(404);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.delete('/api/students/:id',async(req,res)=>{try{await q('DELETE FROM students WHERE id=$1',[req.params.id]);res.sendStatus(204);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/attendance',async(req,res)=>{try{const {date,class_id}=req.query;const r=await q(`SELECT a.*,s.name,s.nis FROM attendance a JOIN students s ON s.id=a.student_id WHERE ($1::date IS NULL OR a.date=$1::date) AND ($2::uuid IS NULL OR a.class_id=$2::uuid) ORDER BY s.name`,[date||null,class_id||null]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/attendance/bulk',async(req,res)=>{try{const {date,class_id,items=[]}=req.body;for(const x of items)await q(`INSERT INTO attendance(class_id,student_id,date,status,note) VALUES($1,$2,$3,$4,$5) ON CONFLICT(student_id,date) DO UPDATE SET status=EXCLUDED.status,note=EXCLUDED.note,class_id=EXCLUDED.class_id,updated_at=NOW()`,[class_id,x.student_id,date,x.status,x.note||null]);res.json({saved:items.length});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/journals',async(_req,res)=>{try{res.json((await q('SELECT * FROM journals ORDER BY date DESC,created_at DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/journals',async(req,res)=>{try{const {teacher_id,class_id,subject_id,date,topic,activities,reflection,attendance_summary}=req.body;const r=await q(`INSERT INTO journals(teacher_id,class_id,subject_id,date,topic,activities,reflection,attendance_summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[teacher_id||null,class_id||null,subject_id||null,date,topic,activities,reflection||null,attendance_summary||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/documents',async(_req,res)=>{try{res.json((await q('SELECT * FROM documents ORDER BY updated_at DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/documents',async(req,res)=>{try{const {teacher_id,class_id,subject_id,type,title,content,status}=req.body;const r=await q(`INSERT INTO documents(teacher_id,class_id,subject_id,type,title,content,status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[teacher_id||null,class_id||null,subject_id||null,type||'modul_ajar',title,content||'',status||'draft']);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/documents/:id',async(req,res)=>{try{const {title,content,status}=req.body;const r=await q('UPDATE documents SET title=$1,content=$2,status=$3,updated_at=NOW() WHERE id=$4 RETURNING *',[title,content||'',status||'draft',req.params.id]);if(!r.rows[0])return res.sendStatus(404);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/assessments',async(_req,res)=>{try{res.json((await q('SELECT * FROM assessments ORDER BY date DESC')).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/assessments',async(req,res)=>{try{const {class_id,subject_id,teacher_id,type,title,date,description}=req.body;const r=await q(`INSERT INTO assessments(class_id,subject_id,teacher_id,type,title,date,description) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[class_id||null,subject_id||null,teacher_id||null,type,title,date,description||null]);res.status(201).json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/assessments/:id/scores',async(req,res)=>{try{res.json((await q('SELECT x.*,s.name,s.nis FROM assessment_scores x JOIN students s ON s.id=x.student_id WHERE assessment_id=$1 ORDER BY s.name',[req.params.id])).rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/generate-curriculum',async(req,res)=>{try{const {docType='CP',level='SD',grade=5,section='A',subject='Matematika',semester='Ganjil',academicYear='2026/2027',chapter='',jpPerWeek=4,weeksGanjil=18,weeksGenap=18,jpPerMeeting=2,meetingMinutes=35}=req.body||{};const payload={docType,level,grade:Number(grade),section,subject,semester,academicYear,chapter,jpPerWeek:Number(jpPerWeek),weeksGanjil:Number(weeksGanjil),weeksGenap:Number(weeksGenap),jpPerMeeting:Number(jpPerMeeting),meetingMinutes:Number(meetingMinutes)};if(process.env.OPENAI_API_KEY){const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id','rumah.pendidikan.go.id']}}],input:buildCurriculumPrompt(payload)});return res.json({mode:'internet-ai',content:response.output_text||'',sources:extractCurriculumSources(response)});}return res.json({mode:'template',content:buildFallbackCurriculum(payload),sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur; dokumen dibuat dengan generator lokal. Tambahkan OPENAI_API_KEY untuk pencarian Internet + AI.'});}catch(e){console.error(e);res.status(500).json({error:'Gagal membuat dokumen kurikulum',detail:e.message});}});
function moduleSectionsFallback(payload){
  const {level='SD',grade=5,subject='Matematika',chapter='Materi Pembelajaran',semester='Ganjil',academicYear='2026/2027',allocationMinutes=70,model='AUTO'}=payload;
  const phase=level==='SD'?(grade<=2?'A':grade<=4?'B':'C'):level==='SMP'?'D':'E/F';
  const m=model==='AUTO'?'Problem Solving':model;
  const mins=Number(allocationMinutes)||70;
  const opening=Math.max(10,Math.round(mins*.15/5)*5), closing=Math.max(10,Math.round(mins*.15/5)*5), core=Math.max(10,mins-opening-closing);
  return {
    identitas:`IDENTITAS MODUL AJAR\n\nJenjang: ${level}\nKelas/Fase: ${grade} / ${phase}\nRombel: ${payload.section||'A'}\nMata Pelajaran: ${subject}\nBab/Materi: ${chapter}\nSemester: ${semester}\nTahun Ajaran: ${academicYear}\nAlokasi Waktu: ${mins} menit (${opening} menit pendahuluan, ${core} menit inti, ${closing} menit penutup)\n\nKompetensi awal: peserta didik memiliki pengetahuan prasyarat yang berkaitan dengan ${chapter}.\nTarget peserta didik: reguler dengan dukungan/diferensiasi sesuai kebutuhan belajar.\nKonteks pembelajaran: kontekstual, inklusif, dan dekat dengan pengalaman peserta didik.`,
    cp:`CAPAIAN PEMBELAJARAN\n\nGunakan CP resmi fase ${phase} mata pelajaran ${subject} sebagai sumber utama. Pemetaan fokus bab: ${chapter}.\n\nElemen/kompetensi yang relevan:\n1. Pengetahuan/konsep yang terkait materi.\n2. Keterampilan menerapkan dan mengomunikasikan pemahaman.\n3. Sikap/karakter yang tampak dalam proses belajar.\n\nCatatan validasi: rumusan CP final wajib dicocokkan dengan dokumen CP resmi terbaru dan KSP/satuan pendidikan.`,
    tp:`TUJUAN PEMBELAJARAN\n\nSetelah pembelajaran, peserta didik diharapkan mampu:\n1. Menjelaskan konsep utama ${chapter} dengan istilah dan representasi yang tepat.\n2. Mengidentifikasi hubungan/unsur penting pada ${chapter}.\n3. Menerapkan konsep ${chapter} untuk menyelesaikan situasi kontekstual.\n4. Menganalisis hasil kerja berdasarkan bukti atau alasan yang relevan.\n5. Mengomunikasikan hasil dan melakukan refleksi terhadap proses belajar.\n\nIndikator ketercapaian: ketepatan konsep, ketepatan penerapan, kualitas alasan/bukti, komunikasi, dan refleksi.`,
    atp:`ALUR TUJUAN PEMBELAJARAN\n\n1. Mengaktifkan pengetahuan awal dan mengidentifikasi kebutuhan belajar.\n2. Memahami konsep/prinsip ${chapter} melalui contoh, observasi, atau eksplorasi.\n3. Menerapkan konsep melalui latihan terbimbing dan kolaboratif.\n4. Menganalisis masalah/konteks nyata dan menentukan strategi penyelesaian.\n5. Menghasilkan atau mempresentasikan bukti pemahaman.\n6. Merefleksi, menerima umpan balik, melakukan perbaikan, remedial, atau pengayaan.\n\nUrutan harus divalidasi terhadap ATP resmi/referensi satuan pendidikan dan alokasi waktu yang tersedia.`,
    profil:`PEMBELAJARAN MENDALAM & 8 DIMENSI PROFIL LULUSAN\n\nPrinsip: berkesadaran, bermakna, dan menggembirakan.\nPengalaman belajar: memahami → mengaplikasi → merefleksi.\n\nDimensi yang diprioritaskan:\n1. Keimanan dan ketakwaan terhadap Tuhan YME\n2. Kewargaan\n3. Penalaran kritis\n4. Kreativitas\n5. Kolaborasi\n6. Kemandirian\n7. Kesehatan\n8. Komunikasi\n\nIntegrasi: pilih 3–5 dimensi yang paling relevan dengan ${chapter}, lalu buktikan melalui aktivitas dan asesmen.`,
    sarpras:`SARANA, PRASARANA, DAN LINGKUNGAN BELAJAR\n\nSumber: buku teks/dokumen resmi, LKPD, media visual, lingkungan sekitar, papan tulis/proyektor, alat tulis, perangkat digital bila tersedia.\n\nLingkungan: aman, inklusif, kolaboratif, memberi ruang bertanya, mencoba, salah, memperbaiki, dan merefleksi.\n\nDiferensiasi: siapkan stimulus sederhana, dukungan bertahap, pilihan media, dan tantangan pengayaan.`,
    model:`MODEL PEMBELAJARAN OTOMATIS\n\nModel: ${m}\nMetode: diskusi, tanya jawab, eksplorasi, praktik/latihan, presentasi, refleksi.\n\nAlasan: model dipilih agar peserta didik aktif memahami, mengaplikasikan, memecahkan masalah, dan mengomunikasikan hasil. Sintaks harus konsisten dengan TP, LKPD, dan asesmen.`,
    langkah:`LANGKAH PEMBELAJARAN TERPERINCI\n\nPENDAHULUAN — ${opening} MENIT\n• Salam, kesiapan, apersepsi, dan koneksi dengan pengalaman peserta didik.\n• Asesmen diagnostik singkat.\n• Menyampaikan tujuan, manfaat, kriteria keberhasilan, dan aktivitas.\n\nINTI — ${core} MENIT\n• Memahami: eksplorasi stimulus, membaca/mengamati, bertanya, dan membangun konsep.\n• Mengaplikasi: latihan, diskusi/kolaborasi, pemecahan masalah, praktik atau produk sesuai model ${m}.\n• Mengomunikasi: presentasi hasil, tanggapan teman, umpan balik guru.\n• Merevisi: memperbaiki jawaban/produk berdasarkan bukti dan umpan balik.\n\nPENUTUP — ${closing} MENIT\n• Menyimpulkan konsep.\n• Refleksi peserta didik dan guru.\n• Menetapkan remedial/pengayaan/tindak lanjut.`,
    asesmen:`ASESMEN LENGKAP\n\n1. Diagnostik: 5 pertanyaan singkat tentang prasyarat, miskonsepsi, dan kesiapan belajar.\n2. Formatif: observasi, pertanyaan cek pemahaman, LKPD, exit ticket, peer/self assessment.\n3. Sumatif: tes tertulis/praktik/produk/performa sesuai karakteristik ${subject}.\n\nKisi-kisi minimal memuat: tujuan pembelajaran, indikator, materi, bentuk soal/tugas, nomor, dan level kognitif.\n\nRubrik 4 tingkat:\n4 = sangat baik/mandiri dan bukti kuat; 3 = baik/tepat dengan sedikit bantuan; 2 = berkembang/perlu arahan; 1 = perlu bimbingan intensif.\n\nKKTP: tetapkan kriteria ketercapaian untuk setiap TP berdasarkan bukti yang dapat diamati, bukan sekadar nilai angka.`,
    lampiran:`LAMPIRAN LENGKAP\n\nA. LKPD: identitas, tujuan, petunjuk, stimulus, pertanyaan pemantik, langkah kerja, tabel data/hasil, ruang jawaban, refleksi, dan penilaian diri.\nB. Bahan Ajar: ringkasan konsep, contoh kontekstual, langkah/strategi, latihan bertingkat, rangkuman, glosarium.\nC. Asesmen Diagnostik: instrumen + kunci/pedoman interpretasi.\nD. Asesmen Formatif: instrumen observasi/cek pemahaman + umpan balik.\nE. Asesmen Sumatif: kisi-kisi, soal/tugas, kunci/pedoman penskoran.\nF. Rubrik: pengetahuan, penerapan, komunikasi, kolaborasi/kemandirian sesuai kebutuhan.\nG. Diferensiasi: konten, proses, produk, dan dukungan untuk peserta didik yang membutuhkan.\nH. Remedial & Pengayaan: aktivitas tindak lanjut yang konkret.\nI. Refleksi: lembar refleksi siswa dan refleksi guru.\nJ. Glosarium dan daftar pustaka/sumber internet.\nK. Halaman pengesahan/tanda tangan: tanggal modul, kepala sekolah + NIP, guru + NIP.`,
    sources:[]
  };
}

function buildModuleSectionsPrompt(payload){
  return `Anda adalah perancang perangkat ajar Indonesia yang sangat teliti. Buat MODUL AJAR PEMBELAJARAN MENDALAM yang lengkap dan siap diedit untuk ${payload.level} kelas ${payload.grade} (fase sesuai jenjang), mata pelajaran ${payload.subject}, bab ${payload.chapter}, semester ${payload.semester}, tahun ajaran ${payload.academicYear}.\n\nRANTAI ACUAN YANG SUDAH DIBUAT (gunakan untuk menjaga konsistensi, jangan menyalin mentah):\nCP: ${String(payload.linkedCP||'belum tersedia').slice(0,12000)}\nTP: ${String(payload.linkedTP||'belum tersedia').slice(0,12000)}\nATP: ${String(payload.linkedATP||'belum tersedia').slice(0,12000)}\nPROMES: ${String(payload.linkedProsem||'belum tersedia').slice(0,8000)}\nPROTA: ${String(payload.linkedProta||'belum tersedia').slice(0,8000)}\n\nGunakan web search. Prioritaskan sumber resmi pemerintah pendidikan: kurikulum.kemdikbud.go.id, kemendikdasmen.go.id, kemdikbud.go.id, rumah.pendidikan.go.id. Untuk informasi normatif/CP/ATP, jangan gunakan blog sebagai otoritas utama. Jangan menyalin panjang dokumen pihak lain; sintesis dengan bahasa baru.\n\nKembalikan HANYA JSON valid dengan keys: identitas, cp, tp, atp, profil, sarpras, model, langkah, asesmen, lampiran, sources. Setiap bagian berupa string HTML atau teks terstruktur yang kaya dan siap diedit guru. sources berupa array URL yang benar-benar ditelusuri.\n\nWAJIB: gunakan prinsip Pembelajaran Mendalam: berkesadaran, bermakna, menggembirakan; pengalaman belajar memahami → mengaplikasi → merefleksi; dan integrasikan 8 dimensi profil lulusan (keimanan/ketakwaan, kewargaan, penalaran kritis, kreativitas, kolaborasi, kemandirian, kesehatan, komunikasi) secara relevan, bukan sekadar daftar.\n\nWAJIB menghubungkan rantai CP → TP → ATP → kegiatan → asesmen. TP harus terukur. ATP harus berurutan dari prasyarat menuju penerapan/pengayaan. Langkah pembelajaran harus rinci dan sesuai model.\n\nWAJIB membuat bagian asesmen lengkap: diagnostik, formatif, sumatif, kisi-kisi, instrumen, kunci/pedoman penskoran, rubrik 4 tingkat, KKTP/kriteria ketercapaian, self-assessment/peer assessment bila relevan.\n\nWAJIB membuat lampiran lengkap: LKPD siap pakai, bahan ajar/ringkasan materi, latihan bertingkat, glosarium, daftar pustaka, asesmen diagnostik, formatif, sumatif, rubrik, remedial, pengayaan, refleksi siswa, refleksi guru, dan format halaman pengesahan/tanda tangan.\n\nALOKASI WAKTU: ${payload.allocationMinutes||70} menit. Rinci pendahuluan, inti, penutup dan pastikan jumlahnya tepat. Model: ${payload.model||'AUTO'}. Jika AUTO, pilih model paling cocok dari karakter TP/materi dan jelaskan alasannya.\n\nJangan mengarang nomor regulasi atau rumusan CP resmi. Jika CP/ATP spesifik tidak ditemukan, nyatakan bahwa guru harus memverifikasi dokumen resmi terbaru dan berikan pemetaan yang aman sebagai rancangan. Data konteks tambahan: ${payload.context||payload.focus||'tidak ada'}.`;
}

app.post('/api/generate-module-sections',async(req,res)=>{
  try{
    const payload={level:'SD',grade:5,section:'A',subject:'Matematika',chapter:'Materi Pembelajaran',semester:'Ganjil',academicYear:'2026/2027',allocationMinutes:70,model:'AUTO',...(req.body||{})};
    const fallback=moduleSectionsFallback(payload);
    if(process.env.OPENAI_API_KEY){
      const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
      const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id','rumah.pendidikan.go.id']}}],input:buildModuleSectionsPrompt(payload)});
      let raw=(response.output_text||'').trim().replace(/^```json\s*/,'').replace(/^```\s*/,'').replace(/```$/,'').trim();
      let parsed;
      try { parsed=JSON.parse(raw); }
      catch(parseErr){ const a=raw.indexOf('{'), b=raw.lastIndexOf('}'); if(a<0||b<=a) throw parseErr; parsed=JSON.parse(raw.slice(a,b+1)); }
      const sections={...fallback,...parsed};
      return res.json({mode:'internet-ai',sections,sources:Array.isArray(parsed.sources)?parsed.sources:[],notice:'10 bagian dibuat AI berdasarkan sumber Internet pendidikan yang ditelusuri. Periksa dan sesuaikan sebelum digunakan.'});
    }
    return res.json({mode:'template',sections:fallback,sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur. Sistem menggunakan generator lokal. Atur OPENAI_API_KEY agar 10 bagian dibuat dengan Internet + AI.'});
  }catch(e){console.error(e);res.status(500).json({error:'Gagal generate 10 bagian modul ajar',detail:e.message});}
});
app.post('/api/generate-module',async(req,res)=>{try{const {level='SD',grade=5,section='A',subject='Matematika',chapter='Materi Pembelajaran',model='AUTO',semester='Ganjil',academicYear='2026/2027',allocationMinutes,linkedCP='',linkedTP='',linkedATP='',linkedProsem='',linkedProta=''}=req.body||{};if(!chapter||!subject)return res.status(400).json({error:'Mata pelajaran dan materi wajib diisi'});const recommendation=recommendLearningModel({subject,chapter,linkedTP,linkedATP}); const selectedModel=model==='AUTO'?recommendation.model:model; const payload={level,grade:Number(grade),section,subject,chapter,model:selectedModel,semester,academicYear,allocationMinutes:Number(allocationMinutes)||undefined,linkedCP,linkedTP,linkedATP,linkedProsem,linkedProta};if(process.env.OPENAI_API_KEY){const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',tools:[{type:'web_search',search_context_size:'high',filters:{allowed_domains:['kemdikbud.go.id','kemendikdasmen.go.id','kurikulum.kemdikbud.go.id']}}],input:buildPrompt(payload)});const content=response.output_text||'';const sources=extractSources(response);return res.json({mode:'internet-ai',content,sources,model:selectedModel,modelRationale:recommendation.rationale,integrated:true,includes:['LKPD','Bahan Ajar','Asesmen']});}const content=buildFallbackModule(payload);return res.json({mode:'template',content,model:selectedModel,modelRationale:recommendation.rationale,sources:['https://kurikulum.kemdikbud.go.id/','https://internal-portal.kemdikbud.go.id/program/312-ruang-gtk'],notice:'OPENAI_API_KEY belum diatur; modul dibuat dengan generator lokal. Tambahkan OPENAI_API_KEY untuk pencarian Internet + AI.'});}catch(e){console.error(e);res.status(500).json({error:'Gagal membuat modul ajar',detail:e.message});}});
app.post('/api/assessments/:id/scores',async(req,res)=>{try{const items=req.body.items||[];for(const x of items)await q(`INSERT INTO assessment_scores(assessment_id,student_id,score,note) VALUES($1,$2,$3,$4) ON CONFLICT(assessment_id,student_id) DO UPDATE SET score=EXCLUDED.score,note=EXCLUDED.note,updated_at=NOW()`,[req.params.id,x.student_id,x.score,x.note||null]);res.json({saved:items.length});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api',(_req,res)=>res.json({name:'Pusat Administrasi Guru API',version:'3.0',status:'running'}));
app.get('/{*splat}',(_req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));
app.use((err,_req,res,_next)=>res.status(500).json({error:err.message}));
const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`Pusat Administrasi Guru running on port ${port}`));
