CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'teacher',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS schools (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,npsn TEXT,address TEXT,phone TEXT,email TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS teachers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID UNIQUE REFERENCES users(id) ON DELETE CASCADE,school_id UUID REFERENCES schools(id) ON DELETE SET NULL,nip TEXT,name TEXT NOT NULL,subject TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS classes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID REFERENCES schools(id) ON DELETE CASCADE,name TEXT NOT NULL,education_level TEXT NOT NULL DEFAULT 'SD',grade TEXT,section TEXT DEFAULT 'A',major TEXT,academic_year TEXT,semester TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS students (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),class_id UUID REFERENCES classes(id) ON DELETE SET NULL,nis TEXT,nisn TEXT,name TEXT NOT NULL,gender TEXT,birth_place TEXT,birth_date DATE,address TEXT,parent_name TEXT,parent_phone TEXT,status TEXT DEFAULT 'aktif',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_classes_level_grade ON classes(education_level,grade); CREATE INDEX IF NOT EXISTS idx_students_name ON students(name); CREATE INDEX IF NOT EXISTS idx_students_class ON students(class_id);
CREATE TABLE IF NOT EXISTS subjects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID REFERENCES schools(id) ON DELETE CASCADE,name TEXT NOT NULL,code TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS schedules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),class_id UUID REFERENCES classes(id) ON DELETE CASCADE,teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL,subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,day_of_week INT NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,room TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS attendance (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),class_id UUID REFERENCES classes(id) ON DELETE SET NULL,student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,date DATE NOT NULL,status TEXT NOT NULL,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(student_id,date));
CREATE TABLE IF NOT EXISTS journals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL,class_id UUID REFERENCES classes(id) ON DELETE SET NULL,subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,date DATE NOT NULL,topic TEXT NOT NULL,activities TEXT,reflection TEXT,attendance_summary TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS curriculum_cp (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID REFERENCES schools(id) ON DELETE CASCADE,subject_id UUID REFERENCES subjects(id) ON DELETE CASCADE,grade TEXT,code TEXT,title TEXT NOT NULL,description TEXT);
CREATE TABLE IF NOT EXISTS curriculum_tp (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),cp_id UUID REFERENCES curriculum_cp(id) ON DELETE CASCADE,code TEXT,title TEXT NOT NULL,description TEXT);
CREATE TABLE IF NOT EXISTS curriculum_atp (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tp_id UUID REFERENCES curriculum_tp(id) ON DELETE CASCADE,sequence INT,title TEXT NOT NULL,description TEXT);
CREATE TABLE IF NOT EXISTS chapters (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),subject_id UUID REFERENCES subjects(id) ON DELETE CASCADE,grade TEXT,title TEXT NOT NULL,sequence INT);
CREATE TABLE IF NOT EXISTS materials (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),chapter_id UUID REFERENCES chapters(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT,content TEXT,learning_objectives TEXT);
CREATE TABLE IF NOT EXISTS documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL,class_id UUID REFERENCES classes(id) ON DELETE SET NULL,subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,type TEXT NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL DEFAULT '',status TEXT DEFAULT 'draft',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assessments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),class_id UUID REFERENCES classes(id) ON DELETE SET NULL,subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL,type TEXT NOT NULL,title TEXT NOT NULL,date DATE NOT NULL,description TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assessment_scores (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),assessment_id UUID NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,score NUMERIC(5,2),note TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(assessment_id,student_id));

ALTER TABLE classes ADD COLUMN IF NOT EXISTS education_level TEXT NOT NULL DEFAULT 'SD';
ALTER TABLE classes ADD COLUMN IF NOT EXISTS section TEXT DEFAULT 'A';
ALTER TABLE classes ADD COLUMN IF NOT EXISTS major TEXT;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS source_urls TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS generation_mode TEXT DEFAULT 'manual';
